app/app/urls.py
from django.contrib import admin
from django.urls import path,include

from home.views import index,contact
from item.views import showCat
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',index,name='index'),
    path('admin/', admin.site.urls),
    path('contact/',contact,name='contact'),
    path('detail/',include('item.urls')),
    path('newitem/',showCat,name='newitem'),
 
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/item/urls.py
from django.urls import path,include

from . import views
app_name='x'

urlpatterns = [
    path('<int:pk>/',views.detail,name='detail'),
    
]

app/home/models.py
from django.db import models

# class student:
    # name=models.CharField(max_length=255)
    # roll=models.ForeignKey(models.CASCADE)
    
    
    

app/item/models.py
from django.db import models
from django.contrib.auth.models import User
class Category(models.Model):
    nameOfCat=models.CharField(max_length=255)
    

    class Meta:
        verbose_name_plural='Categories'
        ordering=['nameOfCat']
        
    def __str__(self):
        return self.nameOfCat
    
class Item(models.Model):
    name=models.CharField(max_length=255)
    category=models.ForeignKey(Category,name='nameOfCat',blank=True,on_delete=models.CASCADE,null=True)
    image=models.ImageField(upload_to='images',null=True,blank=True)
    descriptions=models.TextField(blank=True)
    created_by=models.ForeignKey(User,name='User Name',blank=True,on_delete=models.CASCADE)
    price=models.FloatField(blank=True,null=True)
    id=models.IntegerField(null=False,blank=False,primary_key=True)
    def __str__(self):
       return self.name
    class Meta:
         ordering=['name']

             

app/home/views.py
from django.shortcuts import render
from item.models import Category,Item
def index(request):
     items=Item.objects.all()
     categoris=Category.objects.all()
   
     return render(request,'home/fir.html',{
        'items':items,'categories':categoris,
    })
def contact(request):
   
    return render(request,'home/contact.html')

app/item/views.py
from django.shortcuts import render,get_object_or_404

from .models import Category,Item

def showCat(request):
    items = Item.objects.all()
    return render(request, 'item/item.html', {
        'items': items,
    })
def detail(request,pk):
    item=get_object_or_404(Item,pk=pk)
    return  render(request,'item/detail.html',
           {'item':item},)

app/home/templates/home/base.html
{% load static %}
 <html>
<head>
<link rel="stylesheet"  href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<meta charset="utf-8"> 
<meta name="viewport" content="width=device-width,initial-scale=1.0">

<title>{% block title%}{%endblock%}| Dear!</title>
</head>
<body>
<nav class="navbar navbar-light navbar-expand-md p-0 bg-primary-subtle justify-content-center flex-container sticky-top">
<div >
  <ul class="navbar-nav d-none d-md-flex mr-auto">
           <li class="nav-item"> <a href="/" class="nav-link" >Home</a></li>
            <li class="nav-item"><a href="/newitem/" class="nav-link">New Item </a></li>
            <li class="nav-item"><a href="/" class="nav-link" >Browse</a></li>
            <li class="nav-item"><a href="/" class="nav-link" >Login </a></li>
            <li class="nav-item"><a href="/"  class="nav-link">Sign Up </a></li>
</li>
</div>
</nav>
<div >
 {% block content %}
 
 {% endblock  %} 
</div>
<footer class="bottom">
<div >
<h3> About
</h3>
<p > This company is under MD. Rasel Hossen<br>He is the owner</p>
</div>
<div  class="bottom">
<h3> Menu
</h3>
<ul >
<li><a href="{% url 'contact'%} "class="bottom">Contact</a></li>
<li><a href="#" class="bottom">Privacy Policy</a></li>
</ul>
</div>
</footer>
</body>
</html>

app/home/templates/home/contact.html
{% extends 'home/base.html' %}
{% block title%}Welcome{%endblock%}
{% block content %}

<div ><ul>
<li>I am Rasel</li>
<li>I am Abdullah</li>
</ul>
<h1>This is contact page
</h1>
 {% endblock  %}

app/home/templates/home/fir.html
{% extends 'home/base.html' %}
{% block title%}Welcome{%endblock%}


{% block content %}
<div class="mt-5 px-3 py-5 bg-light rounded" style="overflow: scroll;"   >
  <h2 class="mb-4 text-center">Newest Items</h2>
  <div class="row row-cols-1 row-cols-md-3 g-3"   >

{% for x in items %}
        <div>
        <a href="{% url 'x:detail' x.id %}">
            <div style=" width:60%; height:60%; overflow:hidden;"  >
            <img src="{{x.image.url}}" class="img-fluid rounded "  >
            </div>

        
        </a>
            <div>
            <h3>{{x.name}}</h3>
            </div>
             <div>
            <h3>{{x.price}}</h3>
            </div>

        </div>
{% endfor %}

</div>
</div>


 {% endblock  %}

app/item/templates/item/detail.html
            {% extends 'home/base.html'%}

            {% block title %}{{item.name}} {% endblock%}

            {% block content%}
            <div class="container row row-cols-1 row-cols-md-2 g-300">
             
                <div>
                    <img src=" {{item.image.url}}" style="overflow:hidden;width:400px;height:100%;">
                </div>
                <div>
                    <h1 class="row-cols-1">{{item.name}}</h1>
               
                  <p class="row-gap-sm-2">{{item.descriptions}}</p>
                
                  <p class="row-gap-sm-2">{{item.category}}</p>
                  <h3 class="row-gap-sm-2">{{item.price}}</h3>
                
                  <p class="row-gap-sm-2">{{item.descriptions}}</p>
              
                  <p class="row-gap-sm-2">{{item.category}}</p>
                </div>

            </div>
            {% endblock%}

app/item/templates/item/item.html
{% extends 'home/base.html'%}
   {% block title %}{{item.name}} {% endblock%}
   {% block content %}
        <h1>This is new form</h1>
        <h1>This is new form</h1>
        <h1>This is new form</h1>
        <h1>This is new form</h1>
   {% endblock %}